# Welcome to Jekyll!
#
# Configuration principale du site

title: Mon Portfolio
description: "Bonjour ! Bienvenu sur mon Portfolio, je m'appelle Ethan Piacenti"
github_username: Sygfrid
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone:

include:
  - _pages
  - _pages/en

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Navigation multilingue
navigation:
  enabled: true
  main:
    - title: "Accueil"
      url: /
    - title: "Compétences"
      url: /competences/
    - title: "A Propos"
      url: /about/
    - title: "🇬🇧"
      url: /en/
  en:
    - title: "Home"
      url: /en/
    - title: "Skills"
      url: /en/skills/
    - title: "About"
      url: /en/about/
    - title: "🇫🇷"
      url: /

# Auteur
author:
  name   : "Piacenti Ethan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Etudiant en deuxième année de BUT Réseau&Télécom"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://sygfrid.github.io/ethanpiacenti.github.io/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ethan.pci"
    - label: "Linkedin"
      icon: "afb fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ethan-piacenti/"

# Pied de page
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://sygfrid.github.io/ethanpiacenti.github.io/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ethan.pci"
    - label: "Linkedin"
      icon: "afb fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ethan-piacenti/"

# Defaults : pour appliquer les bons layouts et menus selon le dossier
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      nav: main

  - scope:
      path: "_pages/en"
      type: pages
    values:
      layout: single
      author_profile: true
      nav: en

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
